### ISSUE TITLE
Remove dependency upon CLI `git`

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/web_git#23]
I think this works:

https://repl.it/@raghubetina/test-ruby-git

If we migrate `web_git` to use this gem rather than shelling out to the CLI, then we should be able to use it on repl.it (and anywhere else).

**Comment by jelaniwoods** [comment]
I'm not sure how we can create remotes to push to with [this gem](https://github.com/ruby-git/ruby-git).

**Comment by raghubetina** [comment]
@jelaniwoods [This](https://github.com/ruby-git/ruby-git/pull/168) doesn't look very promising.

Perhaps we can just modify the `.git/config` file ourselves to add the remote?
