### ISSUE TITLE
Can't open ansi2html.sh

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/web_git#3]
I added a line to `bin/setup` to install `diff2html` to the Workspace, but I didn't have time to job my memory on what this meant:

![screen shot 2017-06-28 at 4 24 43 pm](https://user-images.githubusercontent.com/811217/27661039-5f20a19e-5c1e-11e7-919a-e0bc46da7321.png)

**Comment by murugan-r** [comment]
@raghubetina Fixed the issue.
https://github.com/firstdraft/web_git/pull/7
