### ISSUE TITLE
Asset `web_git/application.css` was not declared to be precompiled in production

### ISSUE THREAD

**Issue by jelaniwoods** [firstdraft/web_git#36]
![Screenshot (17)](https://user-images.githubusercontent.com/17581658/68333688-a0c02080-009e-11ea-937e-99e4102cc580.png)

Not sure _**why**_ though.

This was a generated appdev project.

It defaulted to using Rails 6.0.1
when I generate an app with 
```bash
rails __6.0.0_ new appname --rc=.../fd -m ../template.rb
```
this doesn't seem to happen, even if the rails version is 6.0.0

**Comment by jelaniwoods** [comment]
This still seems to happen, but only sometimes. I haven't been able to figure out the actual cause of this. This doesn't happen in omnicalc-api, which was generated 2 weeks ago, but it does happen with new projects that I've generated today.

It can be fixed by adding the assets to the `manifest.js` file, but some projects haven't done that and web_git still works.

**Comment by jelaniwoods** [comment]
@raghubetina This is blocking me and I'm not sure how to proceed. Is there something we can change in `web_git` to precompile the assets? Or should we just add the 2 lines to the manifest.js file in the generated app?

If the former is the "better" solution, then why do apps that are generated with the `_6.0.0_` version specified not require any changes to the web_git gem to work?

**Comment by jelaniwoods** [comment]
Apparently the culprit is none other than `sass-rails`. Or the version of `sprockets` that is required by `sass-rails`.

**Comment by jelaniwoods** [comment]
All projects should use gem `sassc-rails` instead. Not sure what the specific breaking change is.

**Comment by jelaniwoods** [comment]
Seems like the necessary combo is
```ruby
gem 'sprockets', '< 4'
gem 'sassc-rails'
```

**Comment by raghubetina** [comment]
Nice detective work!

**Comment by jelaniwoods** [comment]
I'm still not really sure why the assets stop being included, or whatever is happening. It's strange because according to [this](https://github.com/rails/sprockets/issues/316), version 4 of sprockets should not be giving that error. I might make an issue later, but I'll focus on preparing next weeks assignments first.

**Comment by jelaniwoods** [comment]
Resolved in https://github.com/firstdraft/appdev_template/pull/110
