### ISSUE TITLE
Include an initializer that allows skipping before_actions

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/web_git#42]
What do you think about:

 - Adding a command:

    ```
    rails g web_git:install
    ```

    which places a file inside `config/initializers` called `web_git.rb`
 - Inside that file, 

    ```ruby
    WebGit.setup do |config| do
      # Add any before_action methods that you want to be skipped for WebGit
      config.skip_before_action :authenticate_user!
      config.skip_before_action :force_user_sign_in
    end
    ```

**Comment by jelaniwoods** [comment]
Hmm, so is that web_git installer something that needs to be run after each time they generate an account? Is there a better way to dynamically look at before_actions in application_controller and write those to the initializer? I think this is similar to #40

**Comment by raghubetina** [comment]
For the purposes of the class, we could probably just dynamically detect whether there are `before_actions` defined that match certain patterns (`authenticate_*!` for Devise and `force_*_sign_in` for draft_generators).

If we ever want web_git to be used outside of appdev then we should allow configuration of it. But for now we don't need to, I suppose; you're right.
