### ISSUE TITLE
Research: should we make web_git a small, separate Sinatra app (or something like that)?

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/web_git#49]
There's no reason for web_git to interact with the main Rails application, unlike say, ActiveAdmin. So it need not be a Rails engine. But there's every reason for it _not_ to interact with the Rails app, e.g. to not be broken by a students' bug or locked out by a `before_action`.

Could we make it a standalone Sinatra app that lives in the same folder and is easy to launch in a separate Terminal tab? Would it still be a gem or just a file in the project folder? A gem seems neater.

**Comment by raghubetina** [comment]
@jelaniwoods This might be relevant:

https://thoughtbot.com/blog/how-to-share-a-session-between-sinatra-and-rails

**Comment by jelaniwoods** [comment]
@raghubetina That's really interesting! I didn't consider sharing cookies between apps like that. Although, would this Sinatra app need any authentication or access to the session? I imagine it would just parse the git output and make/push/pull commits.

**Comment by raghubetina** [comment]
@jelaniwoods No, the sharing cookies part is irrelevant to us. But interesting.

More relevant, I thought, was:

 - the realization that we can mount within the same Rack app, and therefore presumably at the same port/Gitpod URL?
 - the two methods of mounting, of which I think the `Rack::Builder` approach seems right for `web_git`?

**Comment by jelaniwoods** [comment]
@raghubetina Initial tests look promising. I've managed to squeeze my test Sinatra app into a gem. There is one minor change to the Rails app that needs to be made, but I intend to have a generator for that in the future. 

If you're curious, here's the gem I'm working on: https://github.com/jelaniwoods-FurtherLearning/jw_git

**Comment by raghubetina** [comment]
Excellent.
