### ISSUE TITLE
Mismatch between CLI git status and web_git git status in changed files?

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/web_git#52]
After creating a new workspace and visiting `/git` for the first time, it shows all the files in the project tree as changed files, even though CLI `git status` does not:

![Screen Shot 2020-04-12 at 3.52.15 PM.png](https://codetreeusercontent.s3.amazonaws.com/uploads/1f558cae-2930-42a5-9958-e1afdd9e1b02/Screen+Shot+2020-04-12+at+3.52.15+PM.png)

![Screen Shot 2020-04-12 at 3.52.25 PM.png](https://codetreeusercontent.s3.amazonaws.com/uploads/1f558cae-2930-42a5-9958-e1afdd9e1b02/Screen+Shot+2020-04-12+at+3.52.25+PM.png)

**Comment by jelaniwoods** [comment]
Sad day 😞 https://github.com/ruby-git/ruby-git/issues/23

**Comment by jelaniwoods** [comment]
To clarify, this is a bug in the gem that was reported over a year ago. A PR was made, but no one has reviewed it and it's now stale.

**Comment by jelaniwoods** [comment]
It's strange because the expected behavior happens in a non rails project like [ruby-practice](https://github.com/appdev-projects/ruby-practice). I'm still investigating a fix.

**Comment by jelaniwoods** [comment]
It seems #74 reverted this change unintentionally. Perhaps two calls to `Git#status` are needed.
