### ISSUE TITLE
Restore the full tree in the git log graph

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/web_git#61]
The git history at the bottom of the page should show the entire graph, not just the current branch. The old gem used something like:

```
git log --oneline --decorate --graph --all
```

**Comment by jelaniwoods** [comment]
This is similar to #55

**Comment by raghubetina** [comment]
@jelaniwoods Indeed it is, my fault. Closing in favor of https://github.com/firstdraft/web_git/issues/55.
